/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Conx;
import Modelo.Empresa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class MainFrame extends javax.swing.JFrame {
    
    public panelConexion con;
    public panelPresentacion presentacion;
    public panelVisualizarEmpresa listEmp;
    public panelVisualizarTrabajador listTr;
    public panelTabla table;
    public static ArrayList<Empresa> empresa = new ArrayList<>();
    public Conx conx;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        
        con = new panelConexion();
        presentacion = new panelPresentacion();
        listTr = new panelVisualizarTrabajador(this);
        conx = new Conx();
        this.pack(); //importante para que se muestren en el mainframe
        this.setLocationRelativeTo(null); //posicionarlo 
        initComponents(); //iniciar componentes
        
        //por defecto, sin conectar a la base de datos esos paneles están desactivados
        
        presentacionMenu.setEnabled(false);
        visualizarMenu.setEnabled(false);
        cerrarMenu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirMenu = new javax.swing.JMenuItem();
        cerrarMenu = new javax.swing.JMenuItem();
        presentacionMenu = new javax.swing.JMenu();
        datosMenu = new javax.swing.JMenuItem();
        visualizarMenu = new javax.swing.JMenu();
        empMenu = new javax.swing.JMenuItem();
        trabMenu = new javax.swing.JMenuItem();
        tablaMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Conectar");

        abrirMenu.setText("Abrir");
        abrirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMenuActionPerformed(evt);
            }
        });
        jMenu1.add(abrirMenu);

        cerrarMenu.setText("Cerrar");
        cerrarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(cerrarMenu);

        jMenuBar1.add(jMenu1);

        presentacionMenu.setText("Presentación");

        datosMenu.setText("Datos");
        datosMenu.setEnabled(false);
        datosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosMenuActionPerformed(evt);
            }
        });
        presentacionMenu.add(datosMenu);

        jMenuBar1.add(presentacionMenu);

        visualizarMenu.setText("Visualizar");

        empMenu.setText("Empresa");
        empMenu.setEnabled(false);
        empMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empMenuActionPerformed(evt);
            }
        });
        visualizarMenu.add(empMenu);

        trabMenu.setText("Trabajador");
        trabMenu.setEnabled(false);
        trabMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabMenuActionPerformed(evt);
            }
        });
        visualizarMenu.add(trabMenu);

        tablaMenu.setText("Tabla de Trabajadores");
        tablaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaMenuActionPerformed(evt);
            }
        });
        visualizarMenu.add(tablaMenu);

        jMenuBar1.add(visualizarMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMenuActionPerformed
        // TODO add your handling code here:
        con = new panelConexion(); //creamos el panel de inicio de sesión
        //lo mostramos con un JOptionPane
        JOptionPane.showMessageDialog(null, con, "Introduzca el usuario y la contraseña", 0);
        
        //llamo al método que me valida las conexiones del usuario, y le paso por parametros, los valores del panel inicioSesion
        
        if (Conx.conexionBD(con.getUsuario(), con.getContra())) { 
            
            //Al iniciar sesión, se activarán y desactivarán los diferentes paneles
            
            
            visualizarMenu.setEnabled(true);
            presentacionMenu.setEnabled(true);
            cerrarMenu.setEnabled(true);
            abrirMenu.setEnabled(false);
            datosMenu.setEnabled(true);
            trabMenu.setEnabled(true);
            empMenu.setEnabled(true);
            tablaMenu.setEnabled(true);
            
            listTr.setNombre(con.getUsuario());

        }
    }//GEN-LAST:event_abrirMenuActionPerformed

    private void cerrarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarMenuActionPerformed
        // TODO add your handling code here:
        // Funcionamiento identico al menú anterior 

        JOptionPane.showMessageDialog(null, "Se ha cerrado correctamente la BDs");

        visualizarMenu.setEnabled(false);
        presentacionMenu.setEnabled(false);
        cerrarMenu.setEnabled(false);
        abrirMenu.setEnabled(true);
        
        
    }//GEN-LAST:event_cerrarMenuActionPerformed

    private void datosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosMenuActionPerformed
        // TODO add your handling code here:
        setContentPane(presentacion);
        this.pack();
    }//GEN-LAST:event_datosMenuActionPerformed

    private void empMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empMenuActionPerformed
        // TODO add your handling code here:
        listEmp = new panelVisualizarEmpresa(this, con.getUsuario());
        setContentPane(listEmp); //y mostramos el panel
        this.pack();
    }//GEN-LAST:event_empMenuActionPerformed

    private void trabMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabMenuActionPerformed
        // TODO add your handling code here:
        try {
            listTr.iniciarDatos(); //inicializamos los datos en el panel vista detalle
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        setContentPane(listTr); //y mostramos el panel
        this.pack();
    }//GEN-LAST:event_trabMenuActionPerformed

    private void tablaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaMenuActionPerformed
        // TODO add your handling code here:
        table = new panelTabla(this, con.getUsuario());
        setContentPane(table); //y mostramos el panel
        this.pack();
    }//GEN-LAST:event_tablaMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirMenu;
    private javax.swing.JMenuItem cerrarMenu;
    private javax.swing.JMenuItem datosMenu;
    private javax.swing.JMenuItem empMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu presentacionMenu;
    private javax.swing.JMenuItem tablaMenu;
    private javax.swing.JMenuItem trabMenu;
    private javax.swing.JMenu visualizarMenu;
    // End of variables declaration//GEN-END:variables

    static ArrayList<Empresa> getEmpresa(){
        return empresa;
    }
    
}
