/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Gestor;
import Modelo.Empresa;
import Modelo.Trabajador;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author alumno
 */
public class panelVisualizarEmpresa extends javax.swing.JPanel {

    public String nombre;
    public Gestor gestor;
    public MainFrame main;
    public int num = 0;
    ArrayList<Empresa> list = new ArrayList();
    float sum=0;
    
    /**
     * 
     * Creates new form panelVisualizarEmpresa
     */
    public panelVisualizarEmpresa(MainFrame main, String usu) {
        this.main=main;
        this.nombre = usu;
        gestor = new Gestor();
        initComponents();
        
        codEText.setEditable(false);
        codEText.setFocusable(false);
        
        fecText.setEditable(false);
        fecText.setFocusable(false);
        
        salTotText.setEditable(false);
        salTotText.setFocusable(false);
        
        nomText.setEditable(false);
        nomText.setFocusable(false);
        
        antButton.setEnabled(false);
        
        getList();
        mostrarDatos(num);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codEText = new javax.swing.JTextField();
        nomText = new javax.swing.JTextField();
        salTotText = new javax.swing.JTextField();
        fecText = new javax.swing.JTextField();
        antButton = new javax.swing.JButton();
        sigButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Listado de Empresas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Salario Total:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de Creación:");

        codEText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nomText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        salTotText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        fecText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        antButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        antButton.setText("Anterior");
        antButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antButtonActionPerformed(evt);
            }
        });

        sigButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sigButton.setText("Siguiente");
        sigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codEText, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(nomText)
                            .addComponent(salTotText)
                            .addComponent(fecText)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(antButton)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55)
                        .addComponent(sigButton)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codEText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(salTotText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fecText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antButton)
                    .addComponent(sigButton)
                    .addComponent(jButton1))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void antButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antButtonActionPerformed
        if (num <= 0) 
            //Si estamos en el primer objeto, se desactiva el boton
            antButton.setEnabled(false);
        else {
            //Sino, se pasa al anterior
            num--;
            if (!sigButton.isEnabled())
                // Si el botón "Siguiente" está desactivado, se activa
                sigButton.setEnabled(true);
            if (num <= 0)
                //Comprobamos si estamos en el primero
                antButton.setEnabled(false);            
        }
        salTotText.setText("");
        mostrarDatos(num);
    }//GEN-LAST:event_antButtonActionPerformed

    private void sigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigButtonActionPerformed
        // TODO add your handling code here:
        if (num >= list.size()-1)
            //Si estamos en el último objeto, desactivamos el boton
            sigButton.setEnabled(false);
        else {
            //Sino, pasamos al siguiente
            num++;
            if (!antButton.isEnabled())
                // Si el botón "Anterior" está desactivado, lo activamos
                antButton.setEnabled(true);
            if (num >= list.size()-1)
                //Comprobamos si estamos en el último
                sigButton.setEnabled(false);
        }
        salTotText.setText("");
        mostrarDatos(num);
    }//GEN-LAST:event_sigButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sum = gestor.calcularSuma(String.valueOf(list.get(num).getCodEmpresa()));
        salTotText.setText(String.valueOf(sum));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antButton;
    private javax.swing.JTextField codEText;
    private javax.swing.JTextField fecText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nomText;
    private javax.swing.JTextField salTotText;
    private javax.swing.JButton sigButton;
    // End of variables declaration//GEN-END:variables
    
    public void mostrarDatos(int num) {
        
        codEText.setText("" + list.get(num).getCodEmpresa());
        nomText.setText(list.get(num).getNomEmpresa());
        fecText.setText("" + list.get(num).getFechaCreacion());
    }
    
    public void getList(){
        try{
            gestor = new Gestor();
            list = gestor.extractEmpresa("select * from empresa");
        }catch(Exception e){
            
        }  
    }
}
