/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.Trabajador;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author alumno
 */
public class panelTabla extends javax.swing.JPanel {

    public MainFrame main;
    public String usuario;
    public Gestor gestor;
    
    /**
     * Creates new form panelTabla
     */
    public panelTabla(MainFrame main, String usuario) {
        
        gestor = new Gestor();
        this.main = main;
        this.usuario = usuario;
        initComponents();
        
        rellenarJTable(trabajadorTabla);
        
        trabajadorTabla.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trabajadorTabla = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Trabajadores");

        trabajadorTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellidos", "Salario", "Fecha de Alta"
            }
        ));
        jScrollPane1.setViewportView(trabajadorTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trabajadorTabla;
    // End of variables declaration//GEN-END:variables

    public void rellenarJTable(JTable jTable1) {

        DefaultTableModel modelo = new DefaultTableModel(); //creamos el modelo

        ArrayList<Object> columnas = new ArrayList<>();//un arraylist de columnas
        
        columnas.removeAll(columnas); //borro las columnas que se crean por defecto al arrastrar el JTable
        
        //y añado las nuevas columnas 
        
        columnas.add("Código");
        columnas.add("Nombre");
        columnas.add("Apellidos");
        columnas.add("Salario");
        columnas.add("Fecha Alta");
        
        //lo añado al modelo 
        
        for(Object col : columnas){
            
            modelo.addColumn(col);
        }

        
        //creo una lista y añadoen la lista los datos indicados
        
        ArrayList<Trabajador> lista;
        lista = gestor.extractTrabajador("select * from trabajador, empresa where trabajador.codEmpresa=empresa.codigoEmpresa and empresa.nomEmpresa = '" + usuario + "'");
        
        //recorro la  lista, y guardo en variables eso datos
        
        for (int i = 0; i < lista.size(); i++) {
            int codigo = lista.get(i).getCodTrabajador();
            String nombre = lista.get(i).getNomTrabajador();
            String apellidos = lista.get(i).getApeTrabajador();
            float salario = lista.get(i).getSalario();
            String fechaAlta = lista.get(i).getFechaAlta().toString();
            
            //añado esos datos en el modelo
            
            modelo.addRow(new Object[]{codigo, nombre, apellidos, salario, fechaAlta});
        }
        
        //importante repetir esta acción
        
        jTable1.setModel(modelo);
    }
}
