/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Gestor;
import Modelo.Trabajador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author alumno
 */
public class panelVisualizarTrabajador extends javax.swing.JPanel {

    public String nombre;
    public Gestor gestor;
    public MainFrame main;
    Trabajador t;
    /**
     * Creates new form panelVisualizar
     */
    public panelVisualizarTrabajador(MainFrame main) {
        this.main=main;
        gestor = new Gestor();
        initComponents();
        
        codTText.setEditable(false);
        codTText.setFocusable(false);
        
        nomText.setEditable(false);
        nomText.setFocusable(false);
        
        apeText.setEditable(false);
        apeText.setFocusable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codTText = new javax.swing.JTextField();
        nomText = new javax.swing.JTextField();
        apeText = new javax.swing.JTextField();
        salText = new javax.swing.JTextField();
        fecText = new javax.swing.JTextField();
        antButton = new javax.swing.JButton();
        sigButton = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        modButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Listado de Trabajadores");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Salario:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Fecha de Alta:");

        codTText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        nomText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        apeText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        salText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        salText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salTextActionPerformed(evt);
            }
        });

        fecText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        antButton.setText("Anterior");
        antButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antButtonActionPerformed(evt);
            }
        });

        sigButton.setText("Siguiente");
        sigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigButtonActionPerformed(evt);
            }
        });

        modButton.setText("Modificar");
        modButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(antButton)
                        .addGap(163, 163, 163)
                        .addComponent(modButton)
                        .addGap(165, 165, 165)
                        .addComponent(sigButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nomText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(apeText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(salText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fecText, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(codTText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(codTText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(apeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(salText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fecText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antButton)
                    .addComponent(sigButton)
                    .addComponent(modButton))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigButtonActionPerformed
        // TODO add your handling code here:
        try {
            mostrarDatos(gestor.sig());
        } catch (SQLException ex) {
            Logger.getLogger(panelVisualizarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sigButtonActionPerformed

    private void antButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antButtonActionPerformed
        // TODO add your handling code here:
        try {
            mostrarDatos(gestor.ant());
        } catch (SQLException ex) {
            Logger.getLogger(panelVisualizarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_antButtonActionPerformed

    private void modButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modButtonActionPerformed
        // TODO add your handling code here:
        gestor.modificarTrabajador(t.getCodTrabajador(), fecText.getText(), salText.getText());
        try {
            actualizar(t.getCodTrabajador());
        } catch (SQLException ex) {
            Logger.getLogger(panelVisualizarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modButtonActionPerformed

    private void salTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_salTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antButton;
    private javax.swing.JTextField apeText;
    private javax.swing.JTextField codTText;
    private javax.swing.JTextField fecText;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton modButton;
    private javax.swing.JTextField nomText;
    private javax.swing.JTextField salText;
    private javax.swing.JButton sigButton;
    // End of variables declaration//GEN-END:variables

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    public void iniciarDatos() throws SQLException {
        
        t = gestor.inicialDetalle("select * from trabajador, empresa where empresa.nomEmpresa = '" + nombre + "' and empresa.codigoEmpresa=Trabajador.codEmpresa");
        mostrarDatos(t);
    }
    
    //muestro los datos iniciados 
    
    public void mostrarDatos(Trabajador t) throws SQLException{
        codTText.setText("" + t.getCodTrabajador());
        nomText.setText(t.getNomTrabajador());
        apeText.setText(t.getApeTrabajador());
        salText.setText("" + t.getSalario());
        fecText.setText("" + t.getFechaAlta());
        
        ImageIcon icon  = new ImageIcon("./src/Fotos/" + t.getFotoTrabajador());
        
        imagen.setIcon(icon);
        
        
        
        //Valido los extremos de la vista 
        
        if(gestor.comprobarAnt())
            antButton.setEnabled(true);
        else
            antButton.setEnabled(false);
        if(gestor.comprobarSig())
            sigButton.setEnabled(true);
        else
            sigButton.setEnabled(false);
    }
    
    //actualizo los cambios en la vista
    
    void actualizar(int codigo) throws SQLException {
        Trabajador t;
        t = gestor.inicialDetalle("select * from trabajador, empresa where empresa.nomEmpresa = '" + nombre + "' and empresa.codigoEmpresa=trabajador.codEmpresa");
        while(t.getCodTrabajador()!=codigo){
            t=gestor.sig();
        }
        mostrarDatos(t);
    }
}