/*CREACION DE TABLAS*/

CREATE TABLE HABILIDADES
(
COD_HA 		CHAR(5)			PRIMARY KEY,
DESC_HA		VARCHAR(30)		NOT NULL 	UNIQUE
);


CREATE TABLE CENTROS
(
COD_CE 				CHAR(4)				PRIMARY KEY, 
DIRECTOR_CE			NUMBER(6),	
NOMB_CE				VARCHAR(30) 		NOT NULL,
DIRECC_CE				VARCHAR(50) 	NOT NULL,
POBLAC_CE				VARCHAR(15) 	NOT NULL	
);

CREATE TABLE DEPARTAMENTOS
(
COD_DE 				CHAR(5)				PRIMARY KEY,
DIRECTOR_DE			NUMBER(6),
DEPTJEFE_DE 		CHAR(5),
CENTRO_DE			CHAR(4)				NOT NULL,
NOMB_DE				VARCHAR2(40)		NOT NULL,
PRESUP_DE			NUMBER(11)			NOT NULL,
TIPODIR_DE			CHAR(1)				NOT NULL
);

CREATE TABLE EMPLEADOS
(
COD_EM				NUMBER(6)		PRIMARY KEY,
DEPT_EM				CHAR(5)			NOT NULL,
EXTIEL_EM			CHAR(9),		
FECINC_EM			DATE			NOT NULL,
FECNACEM			DATE			NOT NULL,
DNI_EM				VARCHAR2(9)		UNIQUE,
NOMB_EM				VARCHAR2(40)	NOT NULL,
NUMHIJ_EM			NUMBER(2)		NOT NULL,
SALARIO_EM			NUMBER(9)		NOT NULL
);

CREATE TABLE HIJOS
(
PADRE_HI			NUMBER(6),
NUMHIJ_HI			NUMBER(2),
FECNAC_HI			DATE			NOT NULL,
NOMB_HI				VARCHAR2(40)	NOT NULL,
CONSTRAINT PK_HIJOS PRIMARY KEY (PADRE_HI, NUMHIJ_HI)
);

CREATE TABLE HABIEMPL
(
CODHA_HE		CHAR(5),
CODEM_HE		NUMBER(6),
CONSTRAINT PK_HABIEMPL PRIMARY KEY (CODHA_HE, CODEM_HE)	
);