/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControlErrores;
import Controlador.DateParse;
import Controlador.PirataDB;
import Modelo.Pirata;
import java.io.File;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Juanfri
 */
public class panelModificarPirata extends javax.swing.JPanel {

    Pirata pirata;
    PirataDB DB;
    public Boolean altaMod = true;
    MainFrame main;
    public panelVisualizarPirata volver;
    
    
    /**
     * Creates new form panelModificarPirata
     */
    public panelModificarPirata(Boolean BMod, MainFrame main, panelVisualizarPirata volver) {
        
        altaMod = BMod;
        this.volver = volver;
        this.main = main;
        initComponents();
        mod.setEnabled(true);
        agr.setEnabled(true);
        eli.setEnabled(true);
        ace.setEnabled(false);
        can.setEnabled(false);
        
        codText.setFocusable(false);
        nomText.setFocusable(false);
        apeTextç.setFocusable(false);
        fecText.setFocusable(false);
        aseText.setFocusable(false);
        armaText.setFocusable(false);
        bandText.setFocusable(false);
        capText.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        codText = new javax.swing.JTextField();
        nomText = new javax.swing.JTextField();
        apeTextç = new javax.swing.JTextField();
        fecText = new javax.swing.JTextField();
        aseText = new javax.swing.JTextField();
        capText = new javax.swing.JTextField();
        bandText = new javax.swing.JTextField();
        armaText = new javax.swing.JTextField();
        fotoText = new javax.swing.JLabel();
        mod = new javax.swing.JButton();
        eli = new javax.swing.JButton();
        agr = new javax.swing.JButton();
        ace = new javax.swing.JButton();
        can = new javax.swing.JButton();
        fotButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("PIRATAS");

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Fecha de Incorporación:");

        jLabel6.setText("Número de asesinatos:");

        jLabel7.setText("Capitán:");

        jLabel8.setText("Banda a la que pertenece:");

        jLabel9.setText("Arma:");

        codText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codTextActionPerformed(evt);
            }
        });

        mod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mod.setText("Modificar");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });

        eli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eli.setText("Eliminar");
        eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliActionPerformed(evt);
            }
        });

        agr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agr.setText("Añadir");
        agr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agrActionPerformed(evt);
            }
        });

        ace.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ace.setText("Aceptar");
        ace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceActionPerformed(evt);
            }
        });

        can.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        can.setText("Cancelar");
        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });

        fotButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fotButton.setText("Cambiar Imagen");
        fotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fotButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mod)
                                .addGap(54, 54, 54)
                                .addComponent(ace)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agr))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fotoText, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codText)
                                .addComponent(nomText)
                                .addComponent(apeTextç)
                                .addComponent(fecText)
                                .addComponent(aseText)
                                .addComponent(capText)
                                .addComponent(bandText)
                                .addComponent(armaText, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(can)
                                .addGap(63, 63, 63)
                                .addComponent(eli)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(codText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(apeTextç, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fecText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(aseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(capText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(bandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(armaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(fotoText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(fotButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mod)
                    .addComponent(eli)
                    .addComponent(agr)
                    .addComponent(ace)
                    .addComponent(can))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
        mod.setEnabled(false);
        agr.setEnabled(false);
        eli.setEnabled(false);
        ace.setEnabled(true);
        can.setEnabled(true);
        nomText.setFocusable(true);
        apeTextç.setFocusable(true);
        fecText.setFocusable(true);
        aseText.setFocusable(true);
        armaText.setFocusable(true);
        
        altaMod = false;
    }//GEN-LAST:event_modActionPerformed

    private void aceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceActionPerformed
        // TODO add your handling code here:
        mod.setEnabled(true);
        agr.setEnabled(true);
        eli.setEnabled(true);
        ace.setEnabled(false);
        can.setEnabled(false);
        
        codText.setFocusable(false);
        nomText.setFocusable(false);
        apeTextç.setFocusable(false);
        fecText.setFocusable(false);
        aseText.setFocusable(false);
        armaText.setFocusable(false);
        bandText.setFocusable(false);
        capText.setFocusable(false);
        
        if(altaMod == true){
            alta(crearPirata());
            JOptionPane.showMessageDialog(null, "Se ha añadido correctamente.");
        }else{
            modificar(pirata);
            JOptionPane.showMessageDialog(null, "Se ha modificado correctamente.");
        }
    }//GEN-LAST:event_aceActionPerformed

    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
        // TODO add your handling code here:
        mod.setEnabled(true);
        agr.setEnabled(true);
        eli.setEnabled(true);
        ace.setEnabled(false);
        can.setEnabled(false);
        
        codText.setFocusable(false);
        nomText.setFocusable(false);
        apeTextç.setFocusable(false);
        fecText.setFocusable(false);
        aseText.setFocusable(false);
        armaText.setFocusable(false);
        bandText.setFocusable(false);
        capText.setFocusable(false);
        iniciarDatos(this.pirata);
    }//GEN-LAST:event_canActionPerformed

    private void agrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agrActionPerformed
        // TODO add your handling code here:
        mod.setEnabled(false);
        agr.setEnabled(false);
        eli.setEnabled(false);
        ace.setEnabled(true);
        can.setEnabled(true);
        
        nomText.setFocusable(true);
        apeTextç.setFocusable(true);
        fecText.setFocusable(true);
        aseText.setFocusable(true);
        armaText.setFocusable(true);
        
        codText.setText("" + DB.findCodigoPirata());
        capText.setText("" + pirata.getCapitan());
        bandText.setText("" + pirata.getCodigoBanda());
        
        nomText.setText("");
        apeTextç.setText("");
        fecText.setText("");
        aseText.setText("");
        armaText.setText("");
        
        altaMod = true;
        
    }//GEN-LAST:event_agrActionPerformed

    private void eliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliActionPerformed
        // TODO add your handling code here:
//        DB.borrarAsig(codText.getText());
        if (JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(null, "¿Desea borrar este jugador?")) {
                DB.borrar(codText.getText());
                volver.mostrarLista(String.valueOf(codText.getText()));
                main.setContentPane(volver);
                main.pack();
        }
        JOptionPane.showMessageDialog(null, "Se ha borrado correctamente.");
        
    }//GEN-LAST:event_eliActionPerformed

    private void fotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser escogerFoto = new JFileChooser();
        File dir = new File("src/Fotos");
        escogerFoto.setCurrentDirectory(dir);
        int option = escogerFoto.showOpenDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            dir = escogerFoto.getSelectedFile();
            ImageIcon icon = new ImageIcon(dir.getAbsolutePath());
            String path = dir.getAbsolutePath();
            String[] link = path.split("/");
            fotoText.setIcon(icon);
        }
    }//GEN-LAST:event_fotButtonActionPerformed

    private void codTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ace;
    private javax.swing.JButton agr;
    private javax.swing.JTextField apeTextç;
    private javax.swing.JTextField armaText;
    private javax.swing.JTextField aseText;
    private javax.swing.JTextField bandText;
    private javax.swing.JButton can;
    private javax.swing.JTextField capText;
    private javax.swing.JTextField codText;
    private javax.swing.JButton eli;
    private javax.swing.JTextField fecText;
    private javax.swing.JButton fotButton;
    private javax.swing.JLabel fotoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton mod;
    private javax.swing.JTextField nomText;
    // End of variables declaration//GEN-END:variables

    public void iniciarDatos(Pirata p) {
        this.pirata = p;
        codText.setText("" + p.getCodPirata());
        nomText.setText(p.getNomPirata());
        apeTextç.setText(p.getApePirata());
        fecText.setText(p.getFechaString());
        aseText.setText("" + p.getAsesinatos());
        capText.setText("" + p.getCapitan());
        
        if(p.getCodigoBanda() == 1){
            bandText.setText("Mugiwara");
        }else if(p.getCodigoBanda()  == 2){
            bandText.setText("RedHair");
        }else if(p.getCodigoBanda()  == 3){
            bandText.setText("Heart");
        }else if(p.getCodigoBanda()  == 4){
            bandText.setText("Buggy");
        }
        
        if(p.getCodigoArma() == 1){
            armaText.setText("Pistola");
        }else if(p.getCodigoArma()  == 2){
            armaText.setText("Escudo");
        }else if(p.getCodigoArma()  == 3){
            armaText.setText("Espada");
        }else if(p.getCodigoArma()  == 4){
            armaText.setText("Katana");
        }else if(p.getCodigoArma()  == 5){
            armaText.setText("Puños");
        }else if(p.getCodigoArma()  == 6){
            armaText.setText("Lanza");
        }else if(p.getCodigoArma()  == 7){
            armaText.setText("Cañon");
        }else if(p.getCodigoArma()  == 8){
            armaText.setText("Cuchillo");
        }
        
        ImageIcon icon = new ImageIcon("./src/Fotos/"+p.getFoto());
        fotoText.setIcon(icon);
    }

    
    private Pirata crearPirata(){
        Pirata p = null;
        try{    
            int codigo = Integer.valueOf(codText.getText());
            String nombre = nomText.getText();
            String apellidos = apeTextç.getText();
            String fecha = fecText.getText();
            GregorianCalendar gc = DateParse.stringToCalendar(fecha);
            int asesinatos = Integer.valueOf(aseText.getText());
            int capitan = Integer.valueOf(capText.getText());
            int banda = Integer.valueOf(bandText.getText());
            int arma = Integer.valueOf(armaText.getText());
            String foto = "1001.jpg";
            
            p = new Pirata(codigo, nombre, apellidos, gc, foto, asesinatos, capitan, banda, arma);
        } catch (ParseException ex) {
            Logger.getLogger(panelModificarPirata.class.getName()).log(Level.SEVERE, null, ex);
        }
        return p;
    }

    private void alta(Pirata p) {
        if (p.getError() == "") {
            try {
                String query = "insert into pirata values(" + p.toString() + ')';
                DB.insertPirata(query);
            } catch (SQLException ex) {
                Logger.getLogger(panelModificarPirata.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, ControlErrores.catchError(7));
        }
    }
    
    private void modificar(Pirata p) {
        if (p.getError() == "") {
            String query = "update pirata set nomPirata = '" + nomText.getText()
                    + "', apePirata = '" + apeTextç.getText()
                    + "', fechaIncorporacion = '" + fecText.getText()
                    + "', asesinatos = " + aseText.getText()
                    + ", codigoArma = " + armaText.getText()
                    + " where codPirata = " + codText.getText();
            DB.updatePirata(query);
        } else {
            JOptionPane.showMessageDialog(null, ControlErrores.catchError(2));
        }
    }
}
