/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControlErrores;
import Controlador.PirataDB;
import Modelo.Pirata;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Juanfri
 */
public class panelVisualizarPirata extends javax.swing.JPanel {

    PirataDB DB;
    public String nombre;
    MainFrame main;
    panelModificarPirata alta;
    panelModificarPirata modificar;
    
    /**
     * Creates new form panelVisualizarPirata
     */
    public panelVisualizarPirata(MainFrame main) {
        this.main = main;
        DB = new PirataDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pirataJList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        pirataJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pirataJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pirataJList);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("PIRATAS");

        jButton1.setText("Alta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        alta = new panelModificarPirata(true, main, this);
        main.setContentPane(alta);
        main.pack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pirataJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pirataJListMouseClicked
        // TODO add your handling code here:
        int index = pirataJList.locationToIndex(evt.getPoint());
        Pirata p;
        if (index != 0) {
            try {

                p = DB.leerI(index);
                modificar = new panelModificarPirata(true, main, this);
                modificar.iniciarDatos(p);
                main.setContentPane(modificar);
                main.pack();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ControlErrores.catchError(2));
            }
        }
    }//GEN-LAST:event_pirataJListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> pirataJList;
    // End of variables declaration//GEN-END:variables

    public void mostrarLista(String nombre) {
        this.nombre = nombre;
        DefaultListModel modelo = new DefaultListModel();
        String linea;
        Object JList;
        pirataJList.setModel(modelo);
        modelo.removeAllElements();
        linea = "Código              Nombre          Apellidos          "
                + "Fecha Incorporación     Asesinatos";     //LOS JLIST SE VEN MUY FEOS
        JList = linea;
        modelo.addElement(JList);
        try {
            DB.InicializarString(nombre);
            while(DB.hasNext()){
                linea = "";
                linea += DB.leerString();
                JList = linea;
                modelo.addElement(JList);
                DB.Siguiente();
            }
            linea = DB.leerString();
            JList = linea;
            modelo.addElement(JList);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, ControlErrores.catchError(12));
        }
    }

}
