/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.*;
import Modelo.Tesoro;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Juanfri
 */
public class panelVisualizarTesoro extends javax.swing.JPanel {

    public TesoroDB BD;
    
    /**
     * Creates new form panelVisualizarTesoro
     */
    public panelVisualizarTesoro() {
        initComponents();
        BD = new TesoroDB();
        codText.setFocusable(false);
        nomText.setFocusable(false);
        bandText.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codText = new javax.swing.JTextField();
        nomText = new javax.swing.JTextField();
        bandText = new javax.swing.JTextField();
        ant = new javax.swing.JButton();
        prin = new javax.swing.JButton();
        last = new javax.swing.JButton();
        sig = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("TESOROS");

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Banda:");

        ant.setText("Anterior");
        ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antActionPerformed(evt);
            }
        });

        prin.setText("Pincipio");
        prin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prinActionPerformed(evt);
            }
        });

        last.setText("Final");
        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });

        sig.setText("Siguiente");
        sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomText)
                            .addComponent(bandText)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(codText, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(ant)
                .addGap(46, 46, 46)
                .addComponent(prin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(last)
                .addGap(48, 48, 48)
                .addComponent(sig)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ant)
                    .addComponent(prin)
                    .addComponent(last)
                    .addComponent(sig))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antActionPerformed
        // TODO add your handling code here:
        try {
            mostrarDatos(BD.Anterior());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, ControlErrores.catchError(6));
        }
    }//GEN-LAST:event_antActionPerformed

    private void prinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prinActionPerformed
        // TODO add your handling code here:
        try {
            mostrarDatos(BD.Primero());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, ControlErrores.catchError(2));
        }
    }//GEN-LAST:event_prinActionPerformed

    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
        // TODO add your handling code here:
        try {
            mostrarDatos(BD.Ultimo());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, ControlErrores.catchError(2));
        }
    }//GEN-LAST:event_lastActionPerformed

    private void sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigActionPerformed
        // TODO add your handling code here:
        try {
            mostrarDatos(BD.Siguiente());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, ControlErrores.catchError(2));
        }
    }//GEN-LAST:event_sigActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ant;
    private javax.swing.JTextField bandText;
    private javax.swing.JTextField codText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton last;
    private javax.swing.JTextField nomText;
    private javax.swing.JButton prin;
    private javax.swing.JButton sig;
    // End of variables declaration//GEN-END:variables


    public void inicializar(String usuario) {
        mostrarDatos(BD.Inicializar("select tesoro.* from tesoro, banda where banda.codBanda = tesoro.bandaPertenece AND banda.nomBanda = '" + usuario + "'"));
    }
    
    private void mostrarDatos(Tesoro t) {
        
        codText.setText("" + t.getCodTesoro());
        nomText.setText("" + t.getNomTesoro());
        
        if(t.getBandaPertenece() == 1){
            bandText.setText("Mugiwara");
        }else if(t.getBandaPertenece() == 2){
            bandText.setText("RedHair");
        }else if(t.getBandaPertenece() == 3){
            bandText.setText("Heart");
        }else if(t.getBandaPertenece() == 4){
            bandText.setText("Buggy");
        }
        
        
        try {
            if (BD.hasNext()) {
                sig.setEnabled(true);
                last.setEnabled(true);
            } else {
                sig.setEnabled(false);
                last.setEnabled(false);
            }
            if (BD.hasPrev()) {
                ant.setEnabled(true);
                prin.setEnabled(true);
            } else {
                ant.setEnabled(false);
                prin.setEnabled(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ControlErrores.catchError(4));
        }
    }
    
}
