/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.*;


/**
 *
 * @author alumno
 */
public class MainFrame extends javax.swing.JFrame {

    private Lista l = new Lista(10);
    private panelPresentacion pres;
    private panelAlta alta;
    private panelListado listado;
    private panelJList listaCompleta;
    private panelFichero fichero;
    private panelOrdenar ordenar;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        pres = new panelPresentacion();
        alta = new panelAlta(l);
        listado = new panelListado(l);
        listaCompleta = new panelJList(l);
        fichero = new panelFichero(l);
        ordenar = new panelOrdenar(l);
        
        cargarDatos();
        
        setContentPane(pres);
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        presItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        altaItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        listadoItem = new javax.swing.JMenuItem();
        jlistItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Presentación");

        presItem.setText("Datos de la Práctica");
        presItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presItemActionPerformed(evt);
            }
        });
        jMenu3.add(presItem);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Insertar");

        altaItem.setText("Agregar Datos");
        altaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaItemActionPerformed(evt);
            }
        });
        jMenu1.add(altaItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Visualizar");

        listadoItem.setText("Listado Completo");
        listadoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoItemActionPerformed(evt);
            }
        });
        jMenu2.add(listadoItem);

        jlistItem.setText("Listado Individual");
        jlistItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistItemActionPerformed(evt);
            }
        });
        jMenu2.add(jlistItem);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Fichero");

        jMenuItem1.setText("Operar con Fichero");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ordenar");

        jMenuItem2.setText("Ordenar ArrayList");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaItemActionPerformed
        // TODO add your handling code here:
        setContentPane(alta);
        this.pack();
    }//GEN-LAST:event_altaItemActionPerformed

    private void listadoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoItemActionPerformed
        // TODO add your handling code here:
        setContentPane(listaCompleta);
        this.pack();
    }//GEN-LAST:event_listadoItemActionPerformed

    private void jlistItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistItemActionPerformed
        // TODO add your handling code here:
        setContentPane(listado);
        this.pack();
    }//GEN-LAST:event_jlistItemActionPerformed

    private void presItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presItemActionPerformed
        // TODO add your handling code here:
        setContentPane(pres);
        this.pack();
    }//GEN-LAST:event_presItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        setContentPane(fichero);
        this.pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setContentPane(ordenar);
        this.pack();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem altaItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jlistItem;
    private javax.swing.JMenuItem listadoItem;
    private javax.swing.JMenuItem presItem;
    // End of variables declaration//GEN-END:variables

    public void cargarDatos(){
        CuentaAhorro ca = new CuentaAhorro("tit", 12.0f, 11.0f, "12/12/2020",12.0f, "qwe");
        CuentaInversion ci= new CuentaInversion("tit3", 12.0f, 11.0f, "12/12/2020", "qwe");
        CuentaCorriente cc = new CuentaCorriente("tit2", 12.0f, 11.0f, "12/12/2020",12.0f, "qwe");
        l.insertarNodo(ca.getNumeroCuenta(), ca);
        l.insertarNodo(cc.getNumeroCuenta(), cc);
        l.insertarNodo(ci.getNumeroCuenta(), ci);
    }
}
