/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.CuentaAhorro;
import Modelo.CuentaCorriente;
import Modelo.CuentaInversion;
import javax.swing.DefaultListModel;

/**
 *
 * @author alumno
 */
public class panelJList extends javax.swing.JPanel {

    private Lista list;
    DefaultListModel modelo = new DefaultListModel();
    Nodo JList;
    
    /**
     * Creates new form panelJList
     */
    public panelJList() {
        initComponents();
    }
    
    public panelJList(Lista l) {
        super();
        initComponents();
        this.list = l;
        
        listadoJList.setModel(modelo);
        modelo.removeAllElements();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoJList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(578, 442));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Listado Completo");

        jScrollPane1.setViewportView(listadoJList);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = new DefaultListModel();
        Object JList;
        String linea;
        
        
        
        listadoJList.setModel(modelo);
        modelo.removeAllElements();



        
        for(int i = 0; i < list.getList().length; i++){
            
            Object c = list.getList()[i].getDato();
            
            JList = list.getList()[i].getDato();
            linea = list.getList()[i].getDato().toString().substring(0, 2);
            if(list.getList()[i] != null){
            
            if(c instanceof CuentaAhorro){

                
            
            CuentaAhorro ca = (CuentaAhorro) c;

            linea = list.getList()[i].getDato().toString().substring(0, 2) + " - " +ca.getNumeroCuenta() + " - " + ca.getProp() + " - " + ca.getSaldo();
            
            
        }else if(c instanceof CuentaInversion){
            
            CuentaInversion ci = (CuentaInversion) c;

            linea = list.getList()[i].getDato().toString().substring(0, 2) + " - " +ci.getNumeroCuenta() + " - " + ci.getProp() + " - " + ci.getSaldo();
        }else if(c instanceof CuentaCorriente){
            
            CuentaCorriente cc = (CuentaCorriente) c;

            linea = list.getList()[i].getDato().toString().substring(0, 2) + " - " +cc.getNumeroCuenta() + " - " + cc.getProp() + " - " + cc.getSaldo();
            
        }
                JList = linea;
                
                modelo.addElement(JList);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listadoJList;
    // End of variables declaration//GEN-END:variables
}
