/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.*;


    

/**
 *
 * @author alumno
 */
public class panelListado extends javax.swing.JPanel {

    private Lista lista;
    int actual = 0;
    private Boolean calcularCumplido;
    
    /**
     * Creates new form panelListado
     */
    public panelListado() {
        initComponents();
        
    }
    
    public panelListado(Lista l) {
//        super();
        initComponents();
        tipLabel.setText("AHORRRO");
        
        antButton.setEnabled(false);
        
        numTextField.setFocusable(false);
        titTextField.setFocusable(false);
        salTextField.setFocusable(false);
        salMinTextField.setFocusable(false);
        fecTextField.setFocusable(false);
        add1TextField.setFocusable(false);
        add2TextField.setFocusable(false);
       
        calButton.setEnabled(false);
        
        
        

        this.lista = l;
        actual = 0;
        this.validate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        add1Label = new javax.swing.JLabel();
        add2Label = new javax.swing.JLabel();
        numTextField = new javax.swing.JTextField();
        titTextField = new javax.swing.JTextField();
        salTextField = new javax.swing.JTextField();
        salMinTextField = new javax.swing.JTextField();
        fecTextField = new javax.swing.JTextField();
        add1TextField = new javax.swing.JTextField();
        add2TextField = new javax.swing.JTextField();
        antButton = new javax.swing.JButton();
        sigButton = new javax.swing.JButton();
        modButton = new javax.swing.JButton();
        calButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(578, 442));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Listado de Cuentas");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Tipo de Cuenta:");

        tipLabel.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        tipLabel.setText("AHORRO");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Número de Cuenta:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Titular:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Saldo:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Saldo Mínimo:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Fecha de Apertura:");

        add1Label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add1Label.setText("Interés Anual:");

        add2Label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add2Label.setText("Localidad:");

        numTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        numTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTextFieldActionPerformed(evt);
            }
        });

        titTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        salTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        salMinTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        fecTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fecTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecTextFieldActionPerformed(evt);
            }
        });

        add1TextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        add2TextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        antButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        antButton.setText("Anterior");
        antButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antButtonActionPerformed(evt);
            }
        });

        sigButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        sigButton.setText("Siguiente");
        sigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigButtonActionPerformed(evt);
            }
        });

        modButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        modButton.setText("Mostrar");
        modButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modButtonActionPerformed(evt);
            }
        });

        calButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calButton.setText("Calcular");
        calButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tipLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(antButton)
                                .addGap(18, 18, 18)
                                .addComponent(modButton)
                                .addGap(32, 32, 32)
                                .addComponent(calButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sigButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(titTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(salTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add1Label)
                    .addComponent(add1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add2Label)
                    .addComponent(add2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antButton)
                    .addComponent(sigButton)
                    .addComponent(modButton)
                    .addComponent(calButton))
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fecTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fecTextFieldActionPerformed

    private void antButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antButtonActionPerformed
        // TODO add your handling code here:
        if (lista.getList()[actual-1] == null) 
                    //Si estamos en el primer objeto, se desactiva el boton
                    antButton.setEnabled(false);
                else {
                    //Sino, se pasa al anterior
                    actual--;
                    if (!sigButton.isEnabled())
                        // Si el botón "Siguiente" está desactivado, se activa
                        sigButton.setEnabled(true);
                    if (actual == 0)
                        //Comprobamos si estamos en el primero
                        antButton.setEnabled(false);
        }
        mostrarDatos();
        Object c = lista.getList()[actual].getDato();
        
        if(c instanceof CuentaAhorro){
            CuentaAhorro ca = (CuentaAhorro) c;
            calcularCumplido = ca.mesesPasados();
            if(calcularCumplido){
                calButton.setEnabled(true);
            }else{
                calButton.setEnabled(false);
            }
        }else if(c instanceof CuentaInversion){
            CuentaInversion ci = (CuentaInversion) c;
            calcularCumplido = ci.mesesPasados();
            if(calcularCumplido){
                calButton.setEnabled(true);
            }else{
                calButton.setEnabled(false);
            }
        }else if(c instanceof CuentaCorriente){
            CuentaCorriente cc = (CuentaCorriente) c;
            calcularCumplido = cc.mesesPasados();
            if(calcularCumplido){
                calButton.setEnabled(true);
            }else{
                calButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_antButtonActionPerformed

    private void sigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigButtonActionPerformed
        // TODO add your handling code here:
        if (lista.getList()[actual+1] == null)
                    //Si estamos en el último objeto, desactivamos el boton
                    sigButton.setEnabled(false);
                else {
                    //Sino, pasamos al siguiente
                    actual++;
                    if (!antButton.isEnabled())
                        // Si el botón "Anterior" está desactivado, lo activamos
                        antButton.setEnabled(true);
                    if (lista.getList()[actual+1] == null)
                        //Comprobamos si estamos en el último
                        sigButton.setEnabled(false);
                }
        mostrarDatos();
        Object c = lista.getList()[actual].getDato();
        
        if(c instanceof CuentaAhorro){
            CuentaAhorro ca = (CuentaAhorro) c;
            calcularCumplido = ca.mesesPasados();
            if(calcularCumplido){
                calButton.setEnabled(true);
            }else{
                calButton.setEnabled(false);
            }
        }else if(c instanceof CuentaInversion){
            CuentaInversion ci = (CuentaInversion) c;
            calcularCumplido = ci.mesesPasados();
            if(calcularCumplido){
                calButton.setEnabled(true);
            }else{
                calButton.setEnabled(false);
            }
        }else if(c instanceof CuentaCorriente){
            CuentaCorriente cc = (CuentaCorriente) c;
            calcularCumplido = cc.mesesPasados();
            if(calcularCumplido){
                calButton.setEnabled(true);
            }else{
                calButton.setEnabled(false);
            }
        }

    }//GEN-LAST:event_sigButtonActionPerformed

    private void modButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modButtonActionPerformed
        // TODO add your handling code here:
        sigButton.setEnabled(true);
        mostrarDatos();
        Object c = lista.getList()[actual].getDato();
        
        if(c instanceof CuentaAhorro){
            CuentaAhorro ca = (CuentaAhorro) c;
            calcularCumplido = ca.mesesPasados();
            if(calcularCumplido){
                calButton.setEnabled(true);
            }else{
                calButton.setEnabled(false);
            }
        }else if(c instanceof CuentaInversion){
            CuentaInversion ci = (CuentaInversion) c;
            calcularCumplido = ci.mesesPasados();
            if(calcularCumplido){
                calButton.setEnabled(true);
            }else{
                calButton.setEnabled(false);
            }
        }else if(c instanceof CuentaCorriente){
            CuentaCorriente cc = (CuentaCorriente) c;
            calcularCumplido = cc.mesesPasados();
            if(calcularCumplido){
                calButton.setEnabled(true);
            }else{
                calButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_modButtonActionPerformed

    private void calButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calButtonActionPerformed
        // TODO add your handling code here:
        Object c = lista.getList()[actual].getDato();
        
        if(c instanceof CuentaAhorro){
            CuentaAhorro ca = (CuentaAhorro) c;
            ca.setSaldo(ca.getSaldo()+ca.getInteresAnual()*CalculoFecha.mesesPasados(ca.getFecha()));
            salTextField.setText(String.valueOf(ca.getSaldo()));
        }else if(c instanceof CuentaInversion){
            CuentaInversion ci = (CuentaInversion) c;
            ci.setSaldo(ci.getSaldo()+(ci.getBeneficioPerdida()/100)*(CalculoFecha.mesesPasados(ci.getFecha())/3));
            ci.setBeneficioPerdida();
            salTextField.setText(String.valueOf(ci.getSaldo()));
            add1TextField.setText(String.valueOf(ci.getBeneficioPerdida()+"%"));
        }else if(c instanceof CuentaCorriente){
            CuentaCorriente cc = (CuentaCorriente) c;
            if("Semestral".equals(add2TextField.getText())){
                cc.setSaldo(cc.getSaldo()+cc.getComision()*CalculoFecha.mesesPasados(cc.getFecha())/6);
                salTextField.setText(String.valueOf(cc.getSaldo()));
            }else if("Anual".equals(add2TextField.getText())){
                cc.setSaldo(cc.getSaldo()+cc.getComision()*CalculoFecha.mesesPasados(cc.getFecha())/12);
                salTextField.setText(String.valueOf(cc.getSaldo()));
            }
            
        }
    }//GEN-LAST:event_calButtonActionPerformed

    private void numTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add1Label;
    private javax.swing.JTextField add1TextField;
    private javax.swing.JLabel add2Label;
    private javax.swing.JTextField add2TextField;
    private javax.swing.JButton antButton;
    private javax.swing.JButton calButton;
    private javax.swing.JTextField fecTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton modButton;
    private javax.swing.JTextField numTextField;
    private javax.swing.JTextField salMinTextField;
    private javax.swing.JTextField salTextField;
    private javax.swing.JButton sigButton;
    private javax.swing.JLabel tipLabel;
    private javax.swing.JTextField titTextField;
    // End of variables declaration//GEN-END:variables

    public void mostrarDatos(){
        
        Object c = lista.getList()[actual].getDato();
        
        if(c instanceof CuentaAhorro){

            tipLabel.setText("AHORRO");
            add1Label.setText("Interés Anual:");
            add2Label.setText("Localidad:");
            
            CuentaAhorro ca = (CuentaAhorro) c;

            numTextField.setText(String.valueOf(ca.getNumeroCuenta()));
            titTextField.setText(ca.getProp());
            salTextField.setText(String.valueOf(ca.getSaldo()));
            salMinTextField.setText(String.valueOf(ca.getSaldoMinimo()));
            fecTextField.setText(ca.getFecha());
            add1TextField.setText(String.valueOf(ca.getInteresAnual()));
            add2TextField.setText(ca.getLocalidad());
            
            this.validate();
            
        }else if(c instanceof CuentaInversion){
            
            tipLabel.setText("INVERSIÓN");
            add1Label.setText("Beneficio Pérdida:");
            add2Label.setText("Localidad:");
            
            CuentaInversion ci = (CuentaInversion) c;

            numTextField.setText(String.valueOf(ci.getNumeroCuenta()));
            titTextField.setText(ci.getProp());
            salTextField.setText(String.valueOf(ci.getSaldo()));
            salMinTextField.setText(String.valueOf(ci.getSaldoMinimo()));
            fecTextField.setText(ci.getFecha());
            add1TextField.setText(String.valueOf(ci.getBeneficioPerdida())+"%");
            add2TextField.setText(ci.getLocalidad());
            
            this.validate();
            
        }else if(c instanceof CuentaCorriente){
            
            tipLabel.setText("CORRIENTE");
            add1Label.setText("Comisión:");
            add2Label.setText("Tipo Comusión:");
            
            CuentaCorriente cc = (CuentaCorriente) c;

            numTextField.setText(String.valueOf(cc.getNumeroCuenta()));
            titTextField.setText(cc.getProp());
            salTextField.setText(String.valueOf(cc.getSaldo()));
            salMinTextField.setText(String.valueOf(cc.getSaldoMinimo()));
            fecTextField.setText(cc.getFecha());
            add1TextField.setText(String.valueOf(cc.getComision()));
            add2TextField.setText(cc.getTipoComision());
            
            this.validate();
        }
    }

    
    
}
